### ISSUE TITLE
Uncaught (in promise) TypeError: object is not a constructor

### ISSUE THREAD

**Issue by janbaer** [blacksonic/angular2-es6-starter#1] opened 2015-12-31 10:47 UTC
I'm getting this error in the console shown. You too? But the app is running...

**Comment by blacksonic** [comment] 2015-12-31 10:52
Can you detail a bit what are you using? I checked it now and in Chrome i get no errors. Using node 4.2.4

**Comment by janbaer** [comment] 2015-12-31 11:30
I did just what you wrote, *npm install* and then *gulp start*. And the I just looked into the console.
I use node 5.0 and the newest version of ChromeCanary. 

The complete error message is.

```
Uncaught (in promise) TypeError: object is not a constructor
    at then (native)
```

Maybe there's a conflict since ChromeCanary supports ES6-Promises without any polyfill. I'm not sure if it's the same with the normal Chrome version.

**Comment by blacksonic** [comment] 2015-12-31 11:53
Can you try to only include only the es6-promise on a webpage? If the error comes there again it is an error in the shim library.

**Comment by janbaer** [comment] 2015-12-31 13:33
I get this error even without importing anything. Maybe it has nothing todo with the sample, because the sample is working and in Firefox I don't get this message. Thanks!

**Comment by simonh1000** [comment] 2016-02-03 15:53
I'm seeing this too

**Comment by blacksonic** [comment] 2016-02-13 10:30
@simonh1000 browser and node version?

**Comment by blacksonic** [comment] 2016-02-14 12:15
You try to navigate to the edit page without logging in?
It might be related to this bug: https://github.com/angular/angular/issues/5169

**Comment by simonh1000** [comment] 2016-02-14 16:15
I switched to something else in the meantime, so I can't be sure, but most likely Ubuntu, node 4/5 and Chrome

**Comment by blacksonic** [comment] 2016-02-14 16:40
Same here and it came out when unauthenticated and got redirected from edit page

**Comment by Serginho** [comment] 2016-03-05 22:58
+1

**Comment by sortegam** [comment] 2016-03-06 08:14
+1

**Comment by blacksonic** [comment] 2016-03-06 09:39
I removed the link to edit when the user is unauthenticated, still an issue? How can you reproduce?

**Comment by davido-valdor** [comment] 2016-03-07 02:42
it happened to me, following the 5min quickstart.... Removing IE script, fix the issue, it seems that the app in chrome works fine....

`-<script src="node_modules/es6-shim/es6-shim.min.js"></script>`

-"es6-shim": "^0.33.3"

**Comment by Johnaka** [comment] 2016-03-09 12:28
i get this after last chrome update

**Comment by blacksonic** [comment] 2016-03-09 12:37
Removing es6-shim helps?

**Comment by blacksonic** [comment] 2016-03-09 12:42
This seems to be an issue in es6-shim, fixed in 0.34: paulmillr/es6-shim#403

**Comment by blacksonic** [comment] 2016-03-09 12:43
Depends on Angular 2 dependencies

**Comment by maxhor** [comment] 2016-03-15 09:50
+1

Message disappears when I move 

`<script src="node_modules/angular2/bundles/angular2-polyfills.js"></script>`

**from** somewhere in between the script listing in index.html  **to** the top of the script listing

**Comment by blacksonic** [comment] 2016-03-15 10:29
Can you show the order of your polifyll files before any angular 2 component?
The current one is this:
```
import 'es6-shim';
import 'reflect-metadata';
import 'zone.js/dist/zone-microtask';
import 'rxjs/Rx';
```

**Comment by tonyawad88** [comment] 2016-03-15 10:39
+1 

Uncaught (in promise) TypeError: object is not a constructor(…)  undefined:(1) [in Chrome]

I can't tell where it's coming from. It is only showing in Chrome for me. Firefox seems fine. 

The app runs fine though. It seems related to the new chrome version ? I am using ionic2. It seems they have the following imports in this order:
es6
reflect
zone-microtask
rxjs = couldn't find the import of this.

Chrome version: Version 49.0.2623.87 (64-bit) (I can see the error)
Firefox versoin: 45.0

**Comment by rvetere** [comment] 2016-03-15 10:42
Just had the same error after switching my computer where i'm working on my current project.

All i had to do is just updating "es6-shim" to the latest version "0.35.0"

Or like i do in this cases - simply remove your dependency from package.json again and re-run

`npm install --save es6-shim`

After that, everything was running fine again..

**Comment by maxhor** [comment] 2016-03-15 13:50
@blacksonic,

I read somewhere that the order of the script is important. But I forgot why the order was important and where I read it. Anyway: 
 
The following order of script included in index.html results in the error  **'Uncaught (in promise) TypeError: object is not a constructor'**


  ```
    <script src="node_modules/es6-shim/es6-shim.min.js"></script>
      <script src="node_modules/angular2/bundles/angular2-polyfills.js"></script>    
```

And the scripts in order underneath  give no error:

  ```
    <script src="node_modules/angular2/bundles/angular2-polyfills.js"></script> 
      <script src="node_modules/es6-shim/es6-shim.min.js"></script>
```

**@all**
     
 I followed rvetere suggestion for update es6. That makes no difference. My NPM list is:

```
H:\VSCode\Hero>npm list --depth=0
hero@1.0.0 H:\VSCode\Hero
+-- angular2@2.0.0-beta.9
+-- concurrently@2.0.0
+-- es6-promise@3.1.2
+-- es6-shim@0.33.13
+-- lite-server@2.1.0
+-- UNMET PEER DEPENDENCY reflect-metadata@0.1.3
+-- rxjs@5.0.0-beta.2
+-- systemjs@0.19.6
+-- typescript@1.8.7
`-- zone.js@0.5.15

npm ERR! peer dep missing: reflect-metadata@0.1.2, required by angular2@2.0.0-beta.9
```
 Oh, if anyone has a solution for the 'reflect-metadata@0.1.2, required by angular2@2.0.0-beta.9' : that would be `nice.`

I tried to fix it (amongst otheres) with issuing:

` npm install reflect-metadata `

This gives a bunch of errors, of which the first is: 

```
LINK : fatal error C1001: An internal error has occurred in the compiler. [H:\V
SCode\Hero\node_modules\bufferutil\build\bufferutil.vcxproj]
```

**Comment by blacksonic** [comment] 2016-03-15 14:03
It will give you an error when doing a clean install

**Comment by blacksonic** [comment] 2016-03-15 14:10
Replaced es6-shim with core-js shim, now it won't throw errors in console.

**Closed by blacksonic** 2016-03-15 14:10 UTC

**Comment by ash-rain** [comment] 2016-03-15 18:15
@blacksonic can you give more info? I'm trying to make this work

**Comment by blacksonic** [comment] 2016-03-15 19:00
The es6 polyfill that is required by angular2 throw this error. It can not be solved till the version is upgraded in its the package json. Till then a workaround is to use another shim, which is core-js.

**Comment by vladimir-ivanov** [comment] 2016-03-16 10:30
npm ERR! peerinvalid The package es6-shim@0.35.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular2@2.0.0-beta.9 wants es6-shim@^0.33.3
npm ERR! peerinvalid Peer ng2-material@0.2.11 wants es6-shim@0.33.13

**Comment by blacksonic** [comment] 2016-03-16 10:36
Yes, that happens when you upgrade es6-shim and after do a clean install.

**Comment by jayeshbhalodia** [comment] 2016-03-16 11:55
+1

**Comment by sean-killeen** [comment] 2016-03-16 12:26
+1

**Comment by duyn9uyen** [comment] 2016-03-16 13:07
+1

**Comment by Villanuevand** [comment] 2016-03-16 13:08
+1

**Comment by vladimir-ivanov** [comment] 2016-03-16 13:28
https://github.com/angular/angular/issues/7618

**Comment by blacksonic** [comment] 2016-03-16 13:43
And here the description of the workaround till it is fixed https://github.com/angular/angular/issues/7601

**Comment by ganeshkbhat** [comment] 2016-03-16 14:02
+1

**Comment by whelanp** [comment] 2016-03-16 22:21
+1

**Comment by woolfi182** [comment] 2016-03-16 23:41
+1

**Comment by maxhor** [comment] 2016-03-17 11:59
@ganeshkbhat,

Why you think inverting the position of the files causes an issue in routerLink.? If I swap the files, the message 'object is not a constructor' goes away with no side effects.

I therefore do not understand why  blacksonic says 

> Till then a workaround is to use another shim, which is core-js.

It works with me after swapping the file order

Having said that: in another copy of this same project (it is the sample 'tour of heroes' project from Angular.io) I have ganeshkbhat's problem: must click twice to browse to the specific location. Obviously, something is different in that copy of the project. But I cannot put my finger on it.

**Comment by tarn2206** [comment] 2016-03-17 12:45
Update "es6-shim": "^0.35.0" will fix this

**Comment by blacksonic** [comment] 2016-03-17 13:06
@maxhor 
It solves the problem for now as I said, just clone the latest changes and it will work. It is the same thing as in https://github.com/AngularClass/angular2-webpack-starter

**Comment by ganeshkbhat** [comment] 2016-03-17 14:37
@maxhor when you invert the file placement then the `link behaviour is like text since my anchor tags do not have href. I have to click once to get it behave like a link else anchor link click behaviour is not seen`. I have now upgraded and seems like the issue is gone for the moment (works without change of file placement)

**Comment by maxhor** [comment] 2016-03-17 14:57
For me same thing. (works without change of file placement) So issue seems gone. Without Update "es6-shim": "^0.35.0".

Thanks you all

**Comment by danieldram** [comment] 2016-03-18 17:38
I also updated to core-js, seems to work.

**Comment by IsaacBorrero** [comment] 2016-03-19 03:07
I re-ordered so the "polyfills" script tag is before the "shim" script tag and updated "shim" to 0.35.0.

That solved the problem for me.

**Comment by netbidev** [comment] 2016-03-19 09:13
@IsaacBorrero thanks, your solution helped to fix same problem

**Comment by iBasit** [comment] 2016-04-16 15:45
I'm trying to fix same for [our ionic2 angular2 project](http://github.com/GlobalQuran/mobile-app), but I cant manage to fix.

Can someone guide please..?  If I add polyfill.js script, it gives some other errors.

**Comment by dat12rmi** [comment] 2016-05-26 20:44
As @tarn2206 said - Update to "es6-shim": "^0.35" and it'll fix the problem.

Do this by changing the es6-shim dependency in package.json to `"es6-shim": "^0.35"` and do `npm install`

**Comment by zhuyiif** [comment] 2016-06-10 21:51
+1

**Comment by jbenzshawel** [comment] 2016-06-15 03:09
+1

**Comment by srishiva89** [comment] 2016-07-04 05:43
When I'm running npm test, I'm getting "**Failed: Uncaught (in promise): cordova_not_available**" error.

A:\project\dx2>npm test

> Diagnox@1.0.1 test A:\project\dx2
> gulp --gulpfile test/gulpfile.ts --cwd ./ unit-test

[00:37:15] Requiring external module ts-node/register
[00:37:18] Using gulpfile A:\project\dx2\test\gulpfile.ts
[00:37:18] Starting 'unit-test'...
[00:37:18] Starting 'lint'...
[00:37:18] Starting 'html'...
[00:37:18] Finished 'html' after 561 ms
[00:37:18] Finished 'lint' after 925 ms
[00:37:19] Starting 'karma'...
decorator { '0': [Function], '1': 0, '2': true, '3': undefined }

START:
04 07 2016 00:37:33.256:INFO [framework.browserify]: bundle built
04 07 2016 00:37:33.290:INFO [karma]: Karma v1.1.0 server started at http://localhost:9876/
04 07 2016 00:37:33.291:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
04 07 2016 00:37:33.302:INFO [launcher]: Starting browser PhantomJS
04 07 2016 00:37:34.906:INFO [PhantomJS 2.1.1 (Windows 8 0.0.0)]: Connected on socket /#i-dJ9QVwBsRB9BqzAAAA with id 76578075
  DxApp
    √ initialises with an app
    √ initialises with a root page
    √ initialises with two pages
    √ opens a page
  DashboardPage
    √ initialises
  LabsPage
    × initialises
    × should get a list of labs
    × should use an HTTP call to obtain a lab data
  Utils
    √ resets a control

Finished in 1.906 secs / 1.898 secs

SUMMARY:
√ 6 tests completed
× 3 tests failed

FAILED TESTS:
  LabsPage
    × initialises
      PhantomJS 2.1.1 (Windows 8 0.0.0)
    Failed: Uncaught (in promise): cordova_not_available

    × should get a list of labs
      PhantomJS 2.1.1 (Windows 8 0.0.0)
    Failed: Uncaught (in promise): cordova_not_available

    × should use an HTTP call to obtain a lab data
      PhantomJS 2.1.1 (Windows 8 0.0.0)
    Failed: Uncaught (in promise): cordova_not_available

------------------------------|----------|----------|----------|----------|----------------|
File                          |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
------------------------------|----------|----------|----------|----------|----------------|
 app\                         |      100 |      100 |      100 |      100 |                |
  app.ts                      |      100 |      100 |      100 |      100 |                |
 app\pages\dashboard\         |      100 |      100 |      100 |      100 |                |
  dashboard.ts                |      100 |      100 |      100 |      100 |                |
 app\pages\labs\              |    88.24 |      100 |    66.67 |    81.82 |                |
  labs.ts                     |    88.24 |      100 |    66.67 |    81.82 |    29,30,32,34 |
 app\providers\labs-provider\ |    91.67 |      100 |    66.67 |    91.67 |                |
  labs-provider.ts            |    91.67 |      100 |    66.67 |    91.67 |             16 |
 app\services\                |       80 |      100 |       40 |    83.33 |                |
  utils.ts                    |       80 |      100 |       40 |    83.33 |           8,10 |
------------------------------|----------|----------|----------|----------|----------------|
All files                     |    92.91 |      100 |    74.19 |    91.03 |                |
------------------------------|----------|----------|----------|----------|----------------|

[00:37:37] 'karma' errored after 19 s
[00:37:37] Error: 1
    at formatError (A:\project\dx2\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (A:\project\dx2\node_modules\gulp\bin\gulp.js:195:15)
    at emitOne (events.js:82:20)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (A:\project\dx2\node_modules\gulp\node_modules\orchestrator\index.js:264:8)
    at A:\project\dx2\node_modules\gulp\node_modules\orchestrator\index.js:275:23
    at finish (A:\project\dx2\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:21:8)
    at cb (A:\project\dx2\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:29:3)
    at removeAllListeners (A:\project\dx2\node_modules\karma\lib\server.js:379:7)
    at Server.<anonymous> (A:\project\dx2\node_modules\karma\lib\server.js:390:9)
    at Server.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Server.emit (events.js:166:7)
    at emitCloseNT (net.js:1521:8)
    at nextTickCallbackWith1Arg (node.js:431:9)
    at process._tickCallback (node.js:353:17)
[00:37:37] 'unit-test' errored after 20 s
[00:37:37] Error in plugin 'run-sequence(karma)'
Message:
    karma callback
npm ERR! Test failed.  See above for more details.

labs.spec.ts:-

import {
  ComponentFixture,
  TestComponentBuilder,
}                         from '@angular/compiler/testing';
import {
  beforeEach,
  beforeEachProviders,
  describe,
  expect,
  injectAsync,
  it,
  inject,
  fakeAsync,
}                         from '@angular/core/testing';

import { provide }        from '@angular/core';
import { LabsPage }       from './labs';
import { Utils }          from '../../services/utils';
import {
  Config,
  Form,
  App,
  NavController,
  NavParams,
  Platform,
}                         from 'ionic-angular';

import {
  Http,
  BaseRequestOptions,
  RequestMethod,
} from '@angular/http';

import { MockBackend, MockConnection } from '@angular/http/testing';
import { LabsProvider }         from '../../providers/labs-provider/labs-provider.ts';

class MockClass {
  public get(): any {
    return '';
  }
}

let labsPage: LabsPage = null;
let labsPageFixture: ComponentFixture<any> = null;
let nativeElement: any = null;
let list: any = null;
let mockHttpProvider: any;
 mockHttpProvider = {
  deps: [ MockBackend, BaseRequestOptions ],
  useFactory: (backend: MockBackend, defaultOptions: BaseRequestOptions) : Http => {
    return new Http(backend, defaultOptions);
  },
};

describe('LabsPage', () => {
  beforeEachProviders(() => {
    return [
      LabsProvider,
      MockBackend,
      BaseRequestOptions,
      provide(Http, mockHttpProvider),
      Form,
      provide(NavController, {useClass: MockClass}),
      provide(NavParams, {useClass: MockClass}),
      provide(Config, {useClass: MockClass}),
      provide(App, {useClass: MockClass}),
      provide(Platform, {useClass: MockClass}),
    ];
  });

  beforeEach(injectAsync([TestComponentBuilder], (tcb: TestComponentBuilder) => {
    return tcb
      .createAsync(LabsPage)
      .then((componentFixture: ComponentFixture<any>) => {
        labsPageFixture = componentFixture;
        labsPage = componentFixture.componentInstance;
        labsPageFixture.detectChanges();
        nativeElement = labsPageFixture.nativeElement;
        list = nativeElement.querySelectorAll('ion-list');
      })
      .catch(Utils.promiseCatchHandler);
  }));

  it('initialises', () => {
    expect(labsPage).not.toBeNull();
    expect(labsPageFixture).not.toBeNull();
  });
  it('should get a list of labs', () => {
    expect(list).not.toBeNull();
  });

  it('should use an HTTP call to obtain a lab data', inject([LabsProvider, MockBackend], fakeAsync((provider: LabsProvider, backend: MockBackend) => {
          backend.connections.subscribe((connection: MockConnection) => {
          expect(connection.request.method).toBe(RequestMethod.Get);
          expect(connection.request.url).toBe(
            'https://abc.xxx.aa/v1/yxys/byDist?lat=20.6734434&lng=-103.3747635');
        });
          // provider.getLabList(20.6734434, -103.3747635);
      })));

});


Please help me on this..

**Comment by blacksonic** [comment] 2016-07-04 06:02
Seems unrelated to the issue, cordova is somehow not available
